apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sandbox
type: Opaque
stringData:
  POSTGRES_PASSWORD: "sandbox"
  DB_URL: "postgres://sandbox:sandbox@postgres:5432/sandbox?sslmode=disable"